/*
        C-file generated by ezCircuit Image Converter ezBMP
*/
/*
        Image size H = 8    V = 7

        Convert to B/W 1bit/pixel      Total : 7 Bytes
*/
#define PROGMEM

const unsigned char IMG_celcius_1px_final[] PROGMEM = {
    0xc0,
    0xdc,
    0x22,
    0x20,
    0x20,
    0x22,
    0x1c};

/*
const unsigned short IMG_celcius_1px_final1[] = {
0xc0
0xdc
0x22
0x20
0x20
0x22
1c
};
*/

/*
const unsigned char IMG_celcius_1px_final2[] = {
XX______,
XX_XXX__,
__X___X_,
__X_____,
__X_____,
__X___X_,
___XXX__
};
*/
