/*
        C-file generated by ezCircuit Image Converter ezBMP
*/
/*
        Image size H = 18    V = 9

        Convert to B/W 1bit/pixel      Total : 27 Bytes
*/
#define PROGMEM

const unsigned char IMG_humi_1px_final[] PROGMEM = {
    0x08, 0x1f, 0xc0,
    0x14, 0x20, 0x00,
    0x22, 0x20, 0x00,
    0x41, 0x20, 0x00,
    0xff, 0x9f, 0xc0,
    0x41, 0x02, 0x00,
    0x7f, 0x02, 0x00,
    0x41, 0x02, 0x00,
    0x3e, 0x3f, 0xc0};

/*
const unsigned short IMG_humi_1px_final1[] = {
0x081f,0xc0
0x1420,0x00
0x2220,0x00
0x4120,0x00
0xff9f,0xc0
0x4102,0x00
0x7f02,0x00
0x4102,0x00
0x3e3f,c0
};
*/

/*
const unsigned char IMG_humi_1px_final2[] = {
____X___,___XXXXX,XX______,
___X_X__,__X_____,________,
__X___X_,__X_____,________,
_X_____X,__X_____,________,
XXXXXXXX,X__XXXXX,XX______,
_X_____X,______X_,________,
_XXXXXXX,______X_,________,
_X_____X,______X_,________,
__XXXXX_,__XXXXXX,XX______
};
*/
