/*
        C-file generated by ezCircuit Image Converter ezBMP
*/
/*
        Image size H = 18    V = 9

        Convert to B/W 1bit/pixel      Total : 27 Bytes
*/
#define PROGMEM

const unsigned char IMG_temp_1px_final[] PROGMEM = {
    0x3e, 0x1f, 0xc0,
    0x41, 0x20, 0x00,
    0x41, 0x20, 0x00,
    0x3e, 0x20, 0x00,
    0x08, 0x1f, 0xc0,
    0xff, 0x82, 0x00,
    0x40, 0x02, 0x00,
    0x40, 0x02, 0x00,
    0x7f, 0x3f, 0xc0};

/*
const unsigned short IMG_temp_1px_final1[] = {
0x3e1f,0xc0
0x4120,0x00
0x4120,0x00
0x3e20,0x00
0x081f,0xc0
0xff82,0x00
0x4002,0x00
0x4002,0x00
0x7f3f,c0
};
*/

/*
const unsigned char IMG_temp_1px_final2[] = {
__XXXXX_,___XXXXX,XX______,
_X_____X,__X_____,________,
_X_____X,__X_____,________,
__XXXXX_,__X_____,________,
____X___,___XXXXX,XX______,
XXXXXXXX,X_____X_,________,
_X______,______X_,________,
_X______,______X_,________,
_XXXXXXX,__XXXXXX,XX______
};
*/
